# Generated by Django 4.2.5 on 2023-09-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagerAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='idEquipo',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='idProyecto',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idUsuario',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
