# Generated by Django 4.2.5 on 2023-10-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagerAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='FechaInicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='FechaTermino',
            field=models.DateTimeField(),
        ),
    ]
