# Generated by Django 4.2.5 on 2023-09-21 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagerAPI', '0002_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Fk_equipo_asignado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserManagerAPI.equipo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Fk_proyecto_asignado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserManagerAPI.proyecto'),
        ),
    ]
