# Generated by Django 4.2.5 on 2023-09-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagerAPI', '0003_alter_usuario_fk_equipo_asignado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Usuario',
            field=models.CharField(max_length=50),
        ),
    ]
