# Generated by Django 4.2.5 on 2023-09-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagerAPI', '0004_alter_usuario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='Lider',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
